version: '2'
services:
    microservices:
        build: .
        image: cloud-native-go:1.0.1-alpine
        environment:
            - PORT=9090
        ports:
            - "9090:9090"
    nginx:
        image: "nginx:1.11.9"
        ports: 
            - "8080:80"
        links: 
            - microservices